{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"amostra_evg (1)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "507f25a3-0c79-4bac-bcb6-f4f451316e2b",
        "fromColumn": "dt_matricula",
        "fromTable": "amostra_evg (1)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4f73a3f1-af81-4727-a7fa-8388ddfed552"
      },
      {
        "name": "fe86a795-b423-4b2f-9353-35f464236a00",
        "fromColumn": "dt_fim",
        "fromTable": "amostra_evg (1)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7caad9b2-5bcd-48bb-a370-57818fcca60c"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "amostra_evg (1)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "cod_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0170f36a-2ba4-4d16-955d-d0d36dd1e604",
            "sourceColumn": "cod_matricula",
            "summarizeBy": "none"
          },
          {
            "name": "dt_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4f6988ae-35bf-4cfa-95b2-49c12db414c5",
            "sourceColumn": "dt_matricula",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_4f73a3f1-af81-4727-a7fa-8388ddfed552"
                },
                "isDefault": true,
                "relationship": "507f25a3-0c79-4bac-bcb6-f4f451316e2b"
              }
            ]
          },
          {
            "name": "nacionalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73135847-700f-47ea-b441-5dd26b5cf3a7",
            "sourceColumn": "nacionalidade",
            "summarizeBy": "none"
          },
          {
            "name": "cod_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "739098c2-188f-4898-9a2a-9b276aeb27f0",
            "sourceColumn": "cod_turma",
            "summarizeBy": "sum"
          },
          {
            "name": "nome_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94a7a768-c9df-4818-8a76-6021770153e6",
            "sourceColumn": "nome_turma",
            "summarizeBy": "none"
          },
          {
            "name": "modalidade_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efc7c5df-10e8-41f4-a1c3-7367e352cd73",
            "sourceColumn": "modalidade_turma",
            "summarizeBy": "none"
          },
          {
            "name": "cod_curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9b54e68-4dfe-4d39-8c62-1876e1bdb7e8",
            "sourceColumn": "cod_curso",
            "summarizeBy": "sum"
          },
          {
            "name": "curso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cde58c23-bc32-43a9-b00c-0fcfc15da507",
            "sourceColumn": "curso",
            "summarizeBy": "none"
          },
          {
            "name": "carga_horaria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a56dff22-4de6-4ce1-9dfb-29a617e6f3d2",
            "sourceColumn": "carga_horaria",
            "summarizeBy": "sum"
          },
          {
            "name": "dt_fim",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b0cc6f11-48b7-4f4d-9ead-1863972bbcee",
            "sourceColumn": "dt_fim",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_7caad9b2-5bcd-48bb-a370-57818fcca60c"
                },
                "isDefault": true,
                "relationship": "fe86a795-b423-4b2f-9353-35f464236a00"
              }
            ]
          },
          {
            "name": "sit_turma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1b454ce-8258-4c12-a037-f93c93f69aa1",
            "sourceColumn": "sit_turma",
            "summarizeBy": "none"
          },
          {
            "name": "instituicao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06fc011d-3832-4c3e-b9f4-9f0ececad10a",
            "sourceColumn": "instituicao",
            "summarizeBy": "none"
          },
          {
            "name": "municipio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e35b1e64-ffc0-432b-bfd1-0e533973315c",
            "sourceColumn": "municipio",
            "summarizeBy": "none"
          },
          {
            "name": "estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4a16c99-1c5e-43cd-abbc-0df1f5ab419a",
            "sourceColumn": "estado",
            "summarizeBy": "none"
          },
          {
            "name": "conteudista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7073b57f-d2fc-4044-b2d0-4ea86bce5237",
            "sourceColumn": "conteudista",
            "summarizeBy": "none"
          },
          {
            "name": "materia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18fa8443-7054-4a11-a865-fee446c66467",
            "sourceColumn": "materia",
            "summarizeBy": "none"
          },
          {
            "name": "codigo_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21601a70-5037-4cf9-9139-9c6b4e60f498",
            "sourceColumn": "codigo_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "sexo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8326c44-9a09-4d55-b991-2d81b402b317",
            "sourceColumn": "sexo",
            "summarizeBy": "none"
          },
          {
            "name": "idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68738d42-be94-4111-ab6f-c60df46297b9",
            "sourceColumn": "idade",
            "summarizeBy": "sum"
          },
          {
            "name": "sit_matricula",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d80a259-7bee-4e70-b1fc-54658ccab6a0",
            "sourceColumn": "sit_matricula",
            "summarizeBy": "none"
          },
          {
            "name": "poder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f96e321-d695-429d-b139-7faed0464f96",
            "sourceColumn": "poder",
            "summarizeBy": "none"
          },
          {
            "name": "esfera",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3475572-a130-4f39-b6e8-4c678bb3ba0d",
            "sourceColumn": "esfera",
            "summarizeBy": "none"
          },
          {
            "name": "email_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6eb71bb8-4235-43f9-910f-0117c57fd14e",
            "sourceColumn": "email_pessoa",
            "summarizeBy": "none"
          },
          {
            "name": "telefone_pessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd1d1b14-dab5-48b2-8a9e-0112131df65d",
            "sourceColumn": "telefone_pessoa",
            "summarizeBy": "sum"
          },
          {
            "name": "email_conteudista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d57f2044-96fa-4f34-b80f-5e66b0d5a369",
            "sourceColumn": "email_conteudista",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "814d18b0-37fe-4a2c-a416-d58631222dd9",
        "partitions": [
          {
            "name": "amostra_evg (1)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\isac.freitasf\\Downloads\\amostra_evg (1).csv\"),[Delimiter=\",\", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"cod_matricula\", type text}, {\"dt_matricula\", type datetime}, {\"nacionalidade\", type text}, {\"cod_turma\", Int64.Type}, {\"nome_turma\", type text}, {\"modalidade_turma\", type text}, {\"cod_curso\", Int64.Type}, {\"nome_curso\", type text}, {\"carga_horaria\", Int64.Type}, {\"dt_fim\", type datetime}, {\"sit_turma\", type text}, {\"instituicao\", type text}, {\"municipio_pessoa\", type text}, {\"uf_pessoa\", type text}, {\"conteudista\", type text}, {\"tematica\", type text}, {\"codigo_pessoa\", type text}, {\"sexo\", type text}, {\"idade\", Int64.Type}, {\"sit_matricula\", type text}, {\"poder\", type text}, {\"esfera\", type text}, {\"email_pessoa\", type text}, {\"telefone_pessoa\", Int64.Type}, {\"email_conteudista\", type text}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"tematica\", \"materia\"}, {\"uf_pessoa\", \"estado\"}, {\"nome_curso\", \"curso\"}, {\"municipio_pessoa\", \"municipio\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_2a377d68-e314-4a75-bd00-ef83e88603b8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "772b57de-d568-4f01-b1c2-9dbeb3b1a23e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bef0a891-9ade-4941-8441-55e27de7f1b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4b158435-3dc3-45b5-ad05-9690bdeabb62",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d04db926-2fff-456d-a376-0ad2358e6509",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b8bb1df8-2878-43ac-aeab-8512fcc2e1a5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "339ec15b-fadc-4d12-998b-6a30a0363910",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "00ae28a0-1da3-42bf-95ba-4cbfa92f596b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "5c3968ad-82bd-4f92-bd00-370e736fc649",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "3f4721e0-dc62-4866-9fcc-157ba6fd25c8",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "b2a86c41-ce3a-4cfc-93cc-7b158acaf771",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "e1c88e7c-0fde-49a3-859e-5b3d03c2d344",
                "ordinal": 3
              }
            ],
            "lineageTag": "c073956a-5514-425f-a5f7-9f4c3cb3d993"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3803fdb7-3b2a-4534-a52e-1af2354e53dd",
        "partitions": [
          {
            "name": "DateTableTemplate_2a377d68-e314-4a75-bd00-ef83e88603b8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4f73a3f1-af81-4727-a7fa-8388ddfed552",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bef1d1c2-e725-4474-9381-ac01bedf1185",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ba41088f-25ef-4ccd-a141-efacdfb2bcbe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1dc5dbbb-cf85-415b-89a9-109e5fa5ec3c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f833c7d7-5ad0-46e9-b8bf-9c16647ba9f3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "804c2f1c-0f7f-43d1-8bf1-e0c1131ce637",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5874c851-0fb2-4b00-831b-b78a9ab8bff3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c6e55b36-01e6-4c45-a8d4-b982d97a982b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "3e4c5a1b-a0d0-43e5-a390-861e13c1b7d0",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "1d917ba6-1d0e-47f8-a03e-73bca297ed28",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "be80091b-3223-47e8-b80d-65878f2ced65",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "5dd21091-3690-4557-b233-665bde75838a",
                "ordinal": 3
              }
            ],
            "lineageTag": "7ff59c0e-305e-4a70-bc1c-44d99b45070b"
          }
        ],
        "isHidden": true,
        "lineageTag": "3d9331e0-d493-4a60-a246-1206e5e04039",
        "partitions": [
          {
            "name": "LocalDateTable_4f73a3f1-af81-4727-a7fa-8388ddfed552",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('amostra_evg (1)'[dt_matricula])), 1, 1), Date(Year(MAX('amostra_evg (1)'[dt_matricula])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7caad9b2-5bcd-48bb-a370-57818fcca60c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9fa0da8e-3390-4ad8-a16d-31f02c1345ed",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b48f9a37-c523-4072-ba60-3005651d9c7b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e1f37b6b-4dbd-4b55-a8bf-f38f30c90777",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6562b91c-a0da-49f4-9ef5-875196035d42",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bf6c9406-20fe-41b7-b6e9-28681bfaef0e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "153fd3dc-f8ac-484e-8367-185d0d9b37f8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1af0fc20-908a-4307-bf8c-e051132cd7d4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "1c32e0cf-0827-4f51-97f6-e37dd6613b7f",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9b76c615-9e15-4baf-8c00-dec518a74a52",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "a47dbef8-0bde-4340-ab53-08294e64217e",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "885ea2d9-dc67-4a15-a567-a37c6728b457",
                "ordinal": 3
              }
            ],
            "lineageTag": "158ec5cb-cb00-4f8c-b50f-88f8d64219d2"
          }
        ],
        "isHidden": true,
        "lineageTag": "5b391bca-93b4-449a-a62c-a88ce0c295e4",
        "partitions": [
          {
            "name": "LocalDateTable_7caad9b2-5bcd-48bb-a370-57818fcca60c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('amostra_evg (1)'[dt_fim])), 1, 1), Date(Year(MAX('amostra_evg (1)'[dt_fim])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}